# keep sorted order
# -- ArgoCD Deployment
argo-cd:
  # -- whether to create the namespace or not
  createNamespace: false
  enable: false

# we install it in kube-system namespace so we don't need to create it
# -- AWS EFS CSI Driver
aws-efs-csi-driver:
  enable: false

# -- Capsule
capsule:
  # -- whether to create the namespace or not
  createNamespace: false
  enable: false

# -- Capsule Tenant
capsule-tenant:
  enable: false

# -- Cert Manager
certmanager:
  # -- whether to create the namespace or not
  createNamespace: false
  enable: false

# -- DefectDojo
defectdojo:
  # -- whether to create the namespace or not
  createNamespace: false
  enable: false

dependency-track:
  createNamespace: false
  enable: false

edp:
  createNamespace: false
  enable: false

extensions-oidc:
  createNamespace: false
  enable: false

external-secrets:
  createNamespace: false
  enable: false

# fluent-bit can be installed as a single component
fluent-bit:
  createNamespace: false
  enable: false

harbor:
  createNamespace: false
  enable: false

# Harbor with High Availability
harbor-ha:
  createNamespace: false
  enable: false

# Harbor with HA, OKD Cluster
harbor-ha-okd:
  createNamespace: false
  enable: false

ingress-nginx:
  createNamespace: false
  enable: false

jaeger-operator:
  enable: false
  createNamespace: false

keycloak:
  createNamespace: false
  enable: false

keycloak-postgresql:
  createNamespace: false
  enable: false

minio-operator:
  createNamespace: false
  enable: false

nexus:
  createNamespace: false
  enable: false

# -- Nexus-operator is not deployed without edp-component-operator CRDs
# -- To deploy the CRD, apply the following command:
# -- kubectl apply -f https://raw.githubusercontent.com/epam/edp-component-operator/v0.13.0/deploy-templates/crds/v1.edp.epam.com_edpcomponents.yaml
nexus-operator:
  createNamespace: false
  enable: false

# opensearch includes opensearch, opensearch-dashboards, fluent-bit
opensearch:
  createNamespace: false
  enable: false

opentelemetry-operator:
  enable: false
  createNamespace: false

# Postgres Operator
postgres-operator:
  createNamespace: false
  enable: false

prometheus-operator:
  createNamespace: false
  enable: false

redis-operator:
  createNamespace: false
  enable: false

sonar:
  createNamespace: false
  enable: false

sonar-operator:
  createNamespace: false
  enable: false

storage-class:
  enable: false

tekton-cache:
  createNamespace: true
  enable: true

tekton:
  createNamespace: false
  enable: false

vault:
  createNamespace: false
  enable: false

vault-kms:
  createNamespace: false
  enable: false

vault-okd:
  createNamespace: false
  enable: false
